Implement RegularExpressionPatternRule
phpstan/phpstan-nette pull request #109
Opened 2022-12-02 20:49 UTC by enumag

Solves #108

2022-12-02 20:51 UTC, enumag commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		foreach ($patternType->getConstantArrays() as $constantArrayType) {
I copied this from the rule in PHPStan but I'm wondering if `TypeUtils::getConstantArrays()` should be used here instead similar to `TypeUtils::getConstantStrings()` a few lines above. What's the difference?

2022-12-02 21:05 UTC, enumag commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		foreach ($patternType->getConstantArrays() as $constantArrayType) {
Failed tests say that `$patternType->getConstantArrays()` doesn't exist in older version. Should I increase the required PHPstan version to 1.9.0 where it was added or should I use `TypeUtils`?

2022-12-02 21:10 UTC, enumag commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		foreach ($patternType->getConstantArrays() as $constantArrayType) {
Ah just noticed that `TypeUtils::getConstantArrays()` is actually deprecated so I'll increase the required version then.

2022-12-12 08:22 UTC, enumag commented
@ondrejmirtes What about this one? I'd really like to have the regular expressions validated.

2022-12-12 08:23 UTC, ondrejmirtes commented
@enumag I have 140 unread emails in my inbox. There are other people waiting too + I have my own priorities what to do with the projects. Sorry.

2022-12-12 08:37 UTC, enumag commented
Understood, sorry.

2022-12-16 10:32 UTC, ondrejmirtes requested changes

2022-12-16 10:32 UTC, ondrejmirtes commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		$className = (string) $staticCall->class;
Call `$scope->resolveName()`. This makes for example `self` resolved into a real class name.

2022-12-16 10:32 UTC, ondrejmirtes commented on rules.neon
> +	- PHPStan\Rule\Nette\RegularExpressionPatternRule
Needs to be added only in bleedingEdge.

2022-12-16 10:32 UTC, ondrejmirtes commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		foreach (TypeUtils::getConstantStrings($patternType) as $constantStringType) {
Use `Type::getConstantStrings()` instead.

2022-12-16 10:32 UTC, ondrejmirtes commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		foreach (TypeUtils::getConstantStrings($patternType) as $constantStringType) {
Require `^1.9.4` for that.

2022-12-16 10:59 UTC, enumag commented on rules.neon
> +	- PHPStan\Rule\Nette\RegularExpressionPatternRule
:thinking: How can I do that?

2022-12-16 11:09 UTC, enumag commented on rules.neon
> +	- PHPStan\Rule\Nette\RegularExpressionPatternRule
I tried to copy something from phpstan-doctrine. Hopefully it's correct.

2022-12-16 11:14 UTC, merged

2022-12-16 11:14 UTC, ondrejmirtes commented
Thank you!