RegularExpressionPatternRule: support extended `Nette\Utils\Strings`
phpstan/phpstan-nette pull request #165
Opened 2024-11-14 14:49 UTC by janedbal

2024-11-14 16:09 UTC, ondrejmirtes requested changes

2024-11-14 16:09 UTC, ondrejmirtes commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		if ($caller->getClassReflection() === null || !$caller->getClassReflection()->is(Strings::class)) {
Please do `(new ObjectType(Strings::class))->isSuperTypeOf($caller)` instead.

2024-11-15 13:31 UTC, janedbal commented on src/Rule/Nette/RegularExpressionPatternRule.php
> +		if ($caller->getClassReflection() === null || !$caller->getClassReflection()->is(Strings::class)) {
Done

2024-11-15 13:42 UTC, merged

2024-11-15 13:42 UTC, ondrejmirtes commented
Thank you.